def solving_quadratic_equation(a, b, c):
    raise ValueError("Error")

